### ISSUE TITLE
Does not compile on windows

### ISSUE THREAD

**Issue by nunzioono** [Lokathor/gbemu#1]
Hi very cool project, i've searched within the repo if had any dependencies to install manually before compiling the project but i found nothing. When i try to do it it shows a missing STATUS_DLL_NOT_FOUND on windows:

![image](https://github.com/Lokathor/gbemu/assets/36959525/2dce8752-7cad-4f26-a2bd-afb7483ed0dc)

**Comment by Lokathor** [comment]
Oh, hi. I forgot this was around.

Well, `fermium`, which `beryllium` builds on top of, uses SDL2. You'll need that available. Since you're on Windows you can get SDL2.dll from their github, https://github.com/libsdl-org/SDL/releases/tag/release-2.30.3, and put it in the root folder of the project where you cloned it and it should be detected and let the program run.

**Comment by nunzioono** [comment]
It worked, thanks!
